### ISSUE TITLE
Supports for 1.20

### ISSUE THREAD

**Issue by WongIong** [BananaPuncher714/PublicCrafters#15]
[05:48:39] [Server thread/INFO]: [PublicCrafters] Enabling PublicCrafters v4.13.8
[05:48:39] [Server thread/WARN]: [PublicCrafters] Could not save messages.yml to plugins\PublicCrafters\messages.yml because messages.yml already exists.
[05:48:39] [Server thread/ERROR]: [PublicCrafters] 'v1_20_R1' is not implemented at the moment! Please contact BananaPuncher714 for future support!
[05:48:39] [Server thread/WARN]: java.lang.NoSuchFieldException: b
[05:48:39] [Server thread/WARN]: 	at java.base/java.lang.Class.getField(Class.java:2117)
[05:48:39] [Server thread/WARN]: 	at PublicCrafters-4.13.8.jar//io.github.bananapuncher714.crafters.util.ReflectionUtil.<clinit>(ReflectionUtil.java:259)
[05:48:39] [Server thread/WARN]: 	at PublicCrafters-4.13.8.jar//io.github.bananapuncher714.crafters.PublicCrafters.onEnable(PublicCrafters.java:83)
[05:48:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[05:48:39] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[05:48:39] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[05:48:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[05:48:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:563)
[05:48:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:474)
[05:48:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[05:48:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[05:48:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[05:48:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[05:48:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[05:48:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:48:39] [Server thread/INFO]: [PublicCrafters] Disabling PublicCrafters v4.13.8
[05:48:39] [Server thread/INFO]: [PublicCrafters] Detected version 'v1_20_R1'
[05:48:39] [Server thread/ERROR]: Error occurred while enabling PublicCrafters v4.13.8 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.github.bananapuncher714.crafters.PublicCrafters.registerListeners(PublicCrafters.java:185) ~[PublicCrafters-4.13.8.jar:?]
	at io.github.bananapuncher714.crafters.PublicCrafters.onEnable(PublicCrafters.java:86) ~[PublicCrafters-4.13.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-10]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-10]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.20.jar:git-Paper-10]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.20.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.20.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.jar:git-Paper-10]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.20.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-10]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BananaPuncher714** [comment]
1.20 support is on my todo list, but I do not know when I will have the time.

**Comment by WongIong** [comment]
ok, i will wait

**Comment by BananaPuncher714** [comment]
Version 4.13.9 should support 1.20
