### ISSUE TITLE
IllegalArgumentException: object is not an instance of declaring class (Plazma)

### ISSUE THREAD

**Issue by rmalca** [BananaPuncher714/PublicCrafters#18]
Hi, thanks for the great job you do maintaining this great plugin.

I've been using Plazma (paper based) lately and I'm getting an error when placing an item on the crafting table.

```
[20:40:54 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
[20:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
[20:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
[20:40:54 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.spawn(VirtualItemDisplay.java:107)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.init(VirtualItemDisplay.java:32)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:190)       
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:101)       
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.updateDisplays(CraftDisplay.java:238)
[20:40:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1749)
[20:40:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[20:40:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:40:54 WARN]: java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
[20:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:70)      
[20:40:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[20:40:54 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.update(VirtualItemDisplay.java:182)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.init(VirtualItemDisplay.java:33)
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:190)       
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:101)       
[20:40:54 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.updateDisplays(CraftDisplay.java:238)
[20:40:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:54 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1749)
[20:40:54 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268)
[20:40:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[20:40:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:40:54 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
[20:40:54 WARN]:        at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
[20:40:54 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)      
[20:40:54 WARN]:        ... 15 more
[20:40:55 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.reflect.Method.invoke(Object, Object[])" is null
[20:40:55 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.kill(VirtualItemDisplay.java:202)
[20:40:55 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.VirtualItemDisplay.remove(VirtualItemDisplay.java:43)
[20:40:55 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:163)       
[20:40:55 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.update(CraftDisplay.java:101)       
[20:40:55 WARN]:        at PublicCrafters-4.13.12.jar//io.github.bananapuncher714.crafters.display.CraftDisplay.updateDisplays(CraftDisplay.java:238)
[20:40:55 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:55 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[20:40:55 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1749)
[20:40:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[20:40:55 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
[20:40:55 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268)
[20:40:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[20:40:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

More info:
```
> ver
[20:46:18 INFO]: Current Plazma Version: 1.20.6-DEV-c531844 (MC: 1.20.6)*
* You are running the latest version
```

**Comment by BananaPuncher714** [comment]
Thanks, I'll do some testing with this, hopefully it's not a huge issue for other forks of paper/spigot.

**Comment by BananaPuncher714** [comment]
This problem was caused by me using the wrong reflection methods for 1.20.6... It was using 1.21 methods.
