### ISSUE TITLE
Supports for 1.21.3

### ISSUE THREAD

**Issue by INSide-734** [BananaPuncher714/PublicCrafters#21]

**Comment by Futodama** [comment]
[20:18:03 INFO]: Checking version, please wait...
[20:18:04 INFO]: Current Purpur Version: 1.21.3-2352-96d7ef7 (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.1-2329-803bf62 (MC: 1.21.1)

[19:47:13 WARN]: [PublicCrafters] Could not save messages.yml to plugins\PublicCrafters\messages.yml because messages.yml already exists.
[19:47:13 ERROR]: Error occurred while enabling PublicCrafters v4.13.13 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at PublicCrafters-4.13.13.jar/io.github.bananapuncher714.crafters.PublicCrafters.onEnable(PublicCrafters.java:83) ~[PublicCrafters-4.13.13.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:771) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:533) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:360) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1249) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ClassCastException: class java.util.Collections$UnmodifiableCollection cannot be cast to class java.lang.String (java.util.Collections$UnmodifiableCollection and java.lang.String are in module java.base of loader 'bootstrap')
        at PublicCrafters-4.13.13.jar/io.github.bananapuncher714.crafters.util.ReflectionUtil.<clinit>(ReflectionUtil.java:63) ~[PublicCrafters-4.13.13.jar:?]
        ... 13 more
[19:47:13 INFO]: [PublicCrafters] Disabling PublicCrafters v4.13.13
[19:47:13 ERROR]: Error occurred while disabling PublicCrafters v4.13.13
java.lang.NullPointerException: Cannot invoke "io.github.bananapuncher714.crafters.implementation.api.CraftInventoryManager.unload(org.bukkit.Chunk)" because "this.manager" is null
        at PublicCrafters-4.13.13.jar/io.github.bananapuncher714.crafters.PublicCrafters.unloadChunks(PublicCrafters.java:116) ~[PublicCrafters-4.13.13.jar:?]
        at PublicCrafters-4.13.13.jar/io.github.bananapuncher714.crafters.PublicCrafters.onDisable(PublicCrafters.java:109) ~[PublicCrafters-4.13.13.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:771) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:533) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:360) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1249) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[purpur-1.21.3.jar:1.21.3-2352-96d7ef7]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
